# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Leandro Marques
email: leandro86marques@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Desenvolvedor, amante de frontend e back-end.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://leandrom.com.br" # the base hostname & protocol for your site
twitter_username: leandropma
github_username:  leandromarques

# Build settings
markdown: kramdown
