# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Leandro Marques
email: leandro86marques@gmail.com
description: Engenheiro de Software
phrase:  Apaixonado por desenvolvimento de software
# baseurl: "" # the subpath of your site, e.g. /blog
# url: "" # the base hostname & protocol for your site
twitter_username: leandropma
github_username:  leandromarques
disqus: leandrom
footer_phrase: Feito com Jekyll
highlighter: rouge

# Build settings
markdown: kramdown
